doctrine:
    dbal:
        # Configuration de la base de données
        driver: 'pdo_mysql'
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # Configuration pour le refactoring
        # Les tables sont déjà créées via les scripts SQL
        # schema_filter: ~

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" est typiquement défini par para-test
            dbname_suffix: '_test%env(default::TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
