security:
    password_hashers:
        App\Entity\Horaire\UserSuivi:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Horaire\UserSuivi
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_login

    role_hierarchy:
        ROLE_ADMIN: [ROLE_INTERVENANT, ROLE_FAMILLE]

    access_control:
        - { path: ^/login,                  roles: PUBLIC_ACCESS }
        - { path: ^/logout,                 roles: PUBLIC_ACCESS }
        - { path: ^/register,               roles: PUBLIC_ACCESS }
        - { path: ^/api/register,           roles: PUBLIC_ACCESS }
        - { path: ^/mot-de-passe-oublie,    roles: PUBLIC_ACCESS }
        - { path: ^/admin-mvc,              roles: ROLE_ADMIN }
        - { path: ^/familles-mvc,           roles: ROLE_ADMIN }
        - { path: ^/famille/,               roles: ROLE_FAMILLE }
        - { path: ^/,                       roles: IS_AUTHENTICATED_FULLY }
